//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buffalo.DBTools {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandBar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandBar() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Buffalo.DBTools.CommandBar", typeof(CommandBar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Aktion 的本地化字符串。
        /// </summary>
        internal static string deAction {
            get {
                return ResourceManager.GetString("deAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add-Ins 的本地化字符串。
        /// </summary>
        internal static string deAddins {
            get {
                return ResourceManager.GetString("deAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Erstellen 的本地化字符串。
        /// </summary>
        internal static string deBuild {
            get {
                return ResourceManager.GetString("deBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Klassendiagramm 的本地化字符串。
        /// </summary>
        internal static string deClass_Diagram {
            get {
                return ResourceManager.GetString("deClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Community 的本地化字符串。
        /// </summary>
        internal static string deCommunity {
            get {
                return ResourceManager.GetString("deCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Daten 的本地化字符串。
        /// </summary>
        internal static string deData {
            get {
                return ResourceManager.GetString("deData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Datenbank 的本地化字符串。
        /// </summary>
        internal static string deDatabase {
            get {
                return ResourceManager.GetString("deDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Datenbankdiagramm 的本地化字符串。
        /// </summary>
        internal static string deDatabase_Diagram {
            get {
                return ResourceManager.GetString("deDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debuggen 的本地化字符串。
        /// </summary>
        internal static string deDebug {
            get {
                return ResourceManager.GetString("deDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagramm 的本地化字符串。
        /// </summary>
        internal static string deDiagram {
            get {
                return ResourceManager.GetString("deDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bearbeiten 的本地化字符串。
        /// </summary>
        internal static string deEdit {
            get {
                return ResourceManager.GetString("deEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Datei 的本地化字符串。
        /// </summary>
        internal static string deFile {
            get {
                return ResourceManager.GetString("deFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format 的本地化字符串。
        /// </summary>
        internal static string deFormat {
            get {
                return ResourceManager.GetString("deFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rahmen 的本地化字符串。
        /// </summary>
        internal static string deFrames {
            get {
                return ResourceManager.GetString("deFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hilfe 的本地化字符串。
        /// </summary>
        internal static string deHelp {
            get {
                return ResourceManager.GetString("deHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bild 的本地化字符串。
        /// </summary>
        internal static string deImage {
            get {
                return ResourceManager.GetString("deImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layout 的本地化字符串。
        /// </summary>
        internal static string deLayout {
            get {
                return ResourceManager.GetString("deLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Makros 的本地化字符串。
        /// </summary>
        internal static string deMacros {
            get {
                return ResourceManager.GetString("deMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Projekt 的本地化字符串。
        /// </summary>
        internal static string deProject {
            get {
                return ResourceManager.GetString("deProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query 的本地化字符串。
        /// </summary>
        internal static string deQuery {
            get {
                return ResourceManager.GetString("deQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Abfrage-Designer 的本地化字符串。
        /// </summary>
        internal static string deQuery_Designer {
            get {
                return ResourceManager.GetString("deQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Umgestalten 的本地化字符串。
        /// </summary>
        internal static string deRefactor {
            get {
                return ResourceManager.GetString("deRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ressourcen 的本地化字符串。
        /// </summary>
        internal static string deResources {
            get {
                return ResourceManager.GetString("deResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Schema 的本地化字符串。
        /// </summary>
        internal static string deSchema {
            get {
                return ResourceManager.GetString("deSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Formate 的本地化字符串。
        /// </summary>
        internal static string deStyles {
            get {
                return ResourceManager.GetString("deStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tabelle 的本地化字符串。
        /// </summary>
        internal static string deTable {
            get {
                return ResourceManager.GetString("deTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tabellen-Designer 的本地化字符串。
        /// </summary>
        internal static string deTable_Designer {
            get {
                return ResourceManager.GetString("deTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Team 的本地化字符串。
        /// </summary>
        internal static string deTeam {
            get {
                return ResourceManager.GetString("deTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Testen 的本地化字符串。
        /// </summary>
        internal static string deTest {
            get {
                return ResourceManager.GetString("deTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extras 的本地化字符串。
        /// </summary>
        internal static string deTools {
            get {
                return ResourceManager.GetString("deTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ansicht 的本地化字符串。
        /// </summary>
        internal static string deView {
            get {
                return ResourceManager.GetString("deView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fenster 的本地化字符串。
        /// </summary>
        internal static string deWindow {
            get {
                return ResourceManager.GetString("deWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML 的本地化字符串。
        /// </summary>
        internal static string deXML {
            get {
                return ResourceManager.GetString("deXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action 的本地化字符串。
        /// </summary>
        internal static string enAction {
            get {
                return ResourceManager.GetString("enAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Addins 的本地化字符串。
        /// </summary>
        internal static string enAddins {
            get {
                return ResourceManager.GetString("enAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Build 的本地化字符串。
        /// </summary>
        internal static string enBuild {
            get {
                return ResourceManager.GetString("enBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Class Diagram 的本地化字符串。
        /// </summary>
        internal static string enClass_Diagram {
            get {
                return ResourceManager.GetString("enClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Community 的本地化字符串。
        /// </summary>
        internal static string enCommunity {
            get {
                return ResourceManager.GetString("enCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data 的本地化字符串。
        /// </summary>
        internal static string enData {
            get {
                return ResourceManager.GetString("enData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database 的本地化字符串。
        /// </summary>
        internal static string enDatabase {
            get {
                return ResourceManager.GetString("enDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database Diagram 的本地化字符串。
        /// </summary>
        internal static string enDatabase_Diagram {
            get {
                return ResourceManager.GetString("enDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug 的本地化字符串。
        /// </summary>
        internal static string enDebug {
            get {
                return ResourceManager.GetString("enDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagram 的本地化字符串。
        /// </summary>
        internal static string enDiagram {
            get {
                return ResourceManager.GetString("enDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string enEdit {
            get {
                return ResourceManager.GetString("enEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        internal static string enFile {
            get {
                return ResourceManager.GetString("enFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format 的本地化字符串。
        /// </summary>
        internal static string enFormat {
            get {
                return ResourceManager.GetString("enFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frames 的本地化字符串。
        /// </summary>
        internal static string enFrames {
            get {
                return ResourceManager.GetString("enFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string enHelp {
            get {
                return ResourceManager.GetString("enHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 的本地化字符串。
        /// </summary>
        internal static string enImage {
            get {
                return ResourceManager.GetString("enImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layout 的本地化字符串。
        /// </summary>
        internal static string enLayout {
            get {
                return ResourceManager.GetString("enLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Macros 的本地化字符串。
        /// </summary>
        internal static string enMacros {
            get {
                return ResourceManager.GetString("enMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project 的本地化字符串。
        /// </summary>
        internal static string enProject {
            get {
                return ResourceManager.GetString("enProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query 的本地化字符串。
        /// </summary>
        internal static string enQuery {
            get {
                return ResourceManager.GetString("enQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query Designer 的本地化字符串。
        /// </summary>
        internal static string enQuery_Designer {
            get {
                return ResourceManager.GetString("enQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refactor 的本地化字符串。
        /// </summary>
        internal static string enRefactor {
            get {
                return ResourceManager.GetString("enRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resources 的本地化字符串。
        /// </summary>
        internal static string enResources {
            get {
                return ResourceManager.GetString("enResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Schema 的本地化字符串。
        /// </summary>
        internal static string enSchema {
            get {
                return ResourceManager.GetString("enSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Styles 的本地化字符串。
        /// </summary>
        internal static string enStyles {
            get {
                return ResourceManager.GetString("enStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table 的本地化字符串。
        /// </summary>
        internal static string enTable {
            get {
                return ResourceManager.GetString("enTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Designer 的本地化字符串。
        /// </summary>
        internal static string enTable_Designer {
            get {
                return ResourceManager.GetString("enTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Team 的本地化字符串。
        /// </summary>
        internal static string enTeam {
            get {
                return ResourceManager.GetString("enTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test 的本地化字符串。
        /// </summary>
        internal static string enTest {
            get {
                return ResourceManager.GetString("enTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools 的本地化字符串。
        /// </summary>
        internal static string enTools {
            get {
                return ResourceManager.GetString("enTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        internal static string enView {
            get {
                return ResourceManager.GetString("enView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window 的本地化字符串。
        /// </summary>
        internal static string enWindow {
            get {
                return ResourceManager.GetString("enWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML 的本地化字符串。
        /// </summary>
        internal static string enXML {
            get {
                return ResourceManager.GetString("enXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acción 的本地化字符串。
        /// </summary>
        internal static string esAction {
            get {
                return ResourceManager.GetString("esAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complementos 的本地化字符串。
        /// </summary>
        internal static string esAddins {
            get {
                return ResourceManager.GetString("esAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generar 的本地化字符串。
        /// </summary>
        internal static string esBuild {
            get {
                return ResourceManager.GetString("esBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagrama de clase 的本地化字符串。
        /// </summary>
        internal static string esClass_Diagram {
            get {
                return ResourceManager.GetString("esClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comunidad 的本地化字符串。
        /// </summary>
        internal static string esCommunity {
            get {
                return ResourceManager.GetString("esCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Datos 的本地化字符串。
        /// </summary>
        internal static string esData {
            get {
                return ResourceManager.GetString("esData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base de datos 的本地化字符串。
        /// </summary>
        internal static string esDatabase {
            get {
                return ResourceManager.GetString("esDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagrama de base de datos 的本地化字符串。
        /// </summary>
        internal static string esDatabase_Diagram {
            get {
                return ResourceManager.GetString("esDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Depurar 的本地化字符串。
        /// </summary>
        internal static string esDebug {
            get {
                return ResourceManager.GetString("esDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagrama 的本地化字符串。
        /// </summary>
        internal static string esDiagram {
            get {
                return ResourceManager.GetString("esDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editar 的本地化字符串。
        /// </summary>
        internal static string esEdit {
            get {
                return ResourceManager.GetString("esEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archivo 的本地化字符串。
        /// </summary>
        internal static string esFile {
            get {
                return ResourceManager.GetString("esFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Formato 的本地化字符串。
        /// </summary>
        internal static string esFormat {
            get {
                return ResourceManager.GetString("esFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Marcos 的本地化字符串。
        /// </summary>
        internal static string esFrames {
            get {
                return ResourceManager.GetString("esFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ayuda 的本地化字符串。
        /// </summary>
        internal static string esHelp {
            get {
                return ResourceManager.GetString("esHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imagen 的本地化字符串。
        /// </summary>
        internal static string esImage {
            get {
                return ResourceManager.GetString("esImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diseño 的本地化字符串。
        /// </summary>
        internal static string esLayout {
            get {
                return ResourceManager.GetString("esLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Macros 的本地化字符串。
        /// </summary>
        internal static string esMacros {
            get {
                return ResourceManager.GetString("esMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proyecto 的本地化字符串。
        /// </summary>
        internal static string esProject {
            get {
                return ResourceManager.GetString("esProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consulta 的本地化字符串。
        /// </summary>
        internal static string esQuery {
            get {
                return ResourceManager.GetString("esQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diseñador de consultas 的本地化字符串。
        /// </summary>
        internal static string esQuery_Designer {
            get {
                return ResourceManager.GetString("esQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refactorizar 的本地化字符串。
        /// </summary>
        internal static string esRefactor {
            get {
                return ResourceManager.GetString("esRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recursos 的本地化字符串。
        /// </summary>
        internal static string esResources {
            get {
                return ResourceManager.GetString("esResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Esquema 的本地化字符串。
        /// </summary>
        internal static string esSchema {
            get {
                return ResourceManager.GetString("esSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Estilos 的本地化字符串。
        /// </summary>
        internal static string esStyles {
            get {
                return ResourceManager.GetString("esStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tabla 的本地化字符串。
        /// </summary>
        internal static string esTable {
            get {
                return ResourceManager.GetString("esTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diseñador de tablas 的本地化字符串。
        /// </summary>
        internal static string esTable_Designer {
            get {
                return ResourceManager.GetString("esTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equipo 的本地化字符串。
        /// </summary>
        internal static string esTeam {
            get {
                return ResourceManager.GetString("esTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prueba 的本地化字符串。
        /// </summary>
        internal static string esTest {
            get {
                return ResourceManager.GetString("esTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Herramientas 的本地化字符串。
        /// </summary>
        internal static string esTools {
            get {
                return ResourceManager.GetString("esTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ver 的本地化字符串。
        /// </summary>
        internal static string esView {
            get {
                return ResourceManager.GetString("esView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ventana 的本地化字符串。
        /// </summary>
        internal static string esWindow {
            get {
                return ResourceManager.GetString("esWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML 的本地化字符串。
        /// </summary>
        internal static string esXML {
            get {
                return ResourceManager.GetString("esXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action 的本地化字符串。
        /// </summary>
        internal static string frAction {
            get {
                return ResourceManager.GetString("frAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compléments 的本地化字符串。
        /// </summary>
        internal static string frAddins {
            get {
                return ResourceManager.GetString("frAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Générer 的本地化字符串。
        /// </summary>
        internal static string frBuild {
            get {
                return ResourceManager.GetString("frBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagramme de classes 的本地化字符串。
        /// </summary>
        internal static string frClass_Diagram {
            get {
                return ResourceManager.GetString("frClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Communauté 的本地化字符串。
        /// </summary>
        internal static string frCommunity {
            get {
                return ResourceManager.GetString("frCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Données 的本地化字符串。
        /// </summary>
        internal static string frData {
            get {
                return ResourceManager.GetString("frData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base de données 的本地化字符串。
        /// </summary>
        internal static string frDatabase {
            get {
                return ResourceManager.GetString("frDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Schéma de base de données 的本地化字符串。
        /// </summary>
        internal static string frDatabase_Diagram {
            get {
                return ResourceManager.GetString("frDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Déboguer 的本地化字符串。
        /// </summary>
        internal static string frDebug {
            get {
                return ResourceManager.GetString("frDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Schéma 的本地化字符串。
        /// </summary>
        internal static string frDiagram {
            get {
                return ResourceManager.GetString("frDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modifier 的本地化字符串。
        /// </summary>
        internal static string frEdit {
            get {
                return ResourceManager.GetString("frEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fichier 的本地化字符串。
        /// </summary>
        internal static string frFile {
            get {
                return ResourceManager.GetString("frFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format 的本地化字符串。
        /// </summary>
        internal static string frFormat {
            get {
                return ResourceManager.GetString("frFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frames 的本地化字符串。
        /// </summary>
        internal static string frFrames {
            get {
                return ResourceManager.GetString("frFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ? 的本地化字符串。
        /// </summary>
        internal static string frHelp {
            get {
                return ResourceManager.GetString("frHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 的本地化字符串。
        /// </summary>
        internal static string frImage {
            get {
                return ResourceManager.GetString("frImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disposition 的本地化字符串。
        /// </summary>
        internal static string frLayout {
            get {
                return ResourceManager.GetString("frLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Macros 的本地化字符串。
        /// </summary>
        internal static string frMacros {
            get {
                return ResourceManager.GetString("frMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Projet 的本地化字符串。
        /// </summary>
        internal static string frProject {
            get {
                return ResourceManager.GetString("frProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requête 的本地化字符串。
        /// </summary>
        internal static string frQuery {
            get {
                return ResourceManager.GetString("frQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Concepteur de requêtes 的本地化字符串。
        /// </summary>
        internal static string frQuery_Designer {
            get {
                return ResourceManager.GetString("frQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refactoriser 的本地化字符串。
        /// </summary>
        internal static string frRefactor {
            get {
                return ResourceManager.GetString("frRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ressources 的本地化字符串。
        /// </summary>
        internal static string frResources {
            get {
                return ResourceManager.GetString("frResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Schéma 的本地化字符串。
        /// </summary>
        internal static string frSchema {
            get {
                return ResourceManager.GetString("frSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Styles 的本地化字符串。
        /// </summary>
        internal static string frStyles {
            get {
                return ResourceManager.GetString("frStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tableau 的本地化字符串。
        /// </summary>
        internal static string frTable {
            get {
                return ResourceManager.GetString("frTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Concepteur de tables 的本地化字符串。
        /// </summary>
        internal static string frTable_Designer {
            get {
                return ResourceManager.GetString("frTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 équipe 的本地化字符串。
        /// </summary>
        internal static string frTeam {
            get {
                return ResourceManager.GetString("frTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test 的本地化字符串。
        /// </summary>
        internal static string frTest {
            get {
                return ResourceManager.GetString("frTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outils 的本地化字符串。
        /// </summary>
        internal static string frTools {
            get {
                return ResourceManager.GetString("frTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Affichage 的本地化字符串。
        /// </summary>
        internal static string frView {
            get {
                return ResourceManager.GetString("frView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fenêtre 的本地化字符串。
        /// </summary>
        internal static string frWindow {
            get {
                return ResourceManager.GetString("frWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML 的本地化字符串。
        /// </summary>
        internal static string frXML {
            get {
                return ResourceManager.GetString("frXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Azione 的本地化字符串。
        /// </summary>
        internal static string itAction {
            get {
                return ResourceManager.GetString("itAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Componenti aggiuntivi 的本地化字符串。
        /// </summary>
        internal static string itAddins {
            get {
                return ResourceManager.GetString("itAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Genera 的本地化字符串。
        /// </summary>
        internal static string itBuild {
            get {
                return ResourceManager.GetString("itBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagramma classi 的本地化字符串。
        /// </summary>
        internal static string itClass_Diagram {
            get {
                return ResourceManager.GetString("itClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comunità 的本地化字符串。
        /// </summary>
        internal static string itCommunity {
            get {
                return ResourceManager.GetString("itCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dati 的本地化字符串。
        /// </summary>
        internal static string itData {
            get {
                return ResourceManager.GetString("itData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database 的本地化字符串。
        /// </summary>
        internal static string itDatabase {
            get {
                return ResourceManager.GetString("itDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagramma database 的本地化字符串。
        /// </summary>
        internal static string itDatabase_Diagram {
            get {
                return ResourceManager.GetString("itDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug 的本地化字符串。
        /// </summary>
        internal static string itDebug {
            get {
                return ResourceManager.GetString("itDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagramma 的本地化字符串。
        /// </summary>
        internal static string itDiagram {
            get {
                return ResourceManager.GetString("itDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modifica 的本地化字符串。
        /// </summary>
        internal static string itEdit {
            get {
                return ResourceManager.GetString("itEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        internal static string itFile {
            get {
                return ResourceManager.GetString("itFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Formato 的本地化字符串。
        /// </summary>
        internal static string itFormat {
            get {
                return ResourceManager.GetString("itFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frame 的本地化字符串。
        /// </summary>
        internal static string itFrames {
            get {
                return ResourceManager.GetString("itFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ? 的本地化字符串。
        /// </summary>
        internal static string itHelp {
            get {
                return ResourceManager.GetString("itHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Immagine 的本地化字符串。
        /// </summary>
        internal static string itImage {
            get {
                return ResourceManager.GetString("itImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layout 的本地化字符串。
        /// </summary>
        internal static string itLayout {
            get {
                return ResourceManager.GetString("itLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Macro 的本地化字符串。
        /// </summary>
        internal static string itMacros {
            get {
                return ResourceManager.GetString("itMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progetto 的本地化字符串。
        /// </summary>
        internal static string itProject {
            get {
                return ResourceManager.GetString("itProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query 的本地化字符串。
        /// </summary>
        internal static string itQuery {
            get {
                return ResourceManager.GetString("itQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progettazione query 的本地化字符串。
        /// </summary>
        internal static string itQuery_Designer {
            get {
                return ResourceManager.GetString("itQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Effettua refactoring 的本地化字符串。
        /// </summary>
        internal static string itRefactor {
            get {
                return ResourceManager.GetString("itRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Risorse 的本地化字符串。
        /// </summary>
        internal static string itResources {
            get {
                return ResourceManager.GetString("itResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Schema 的本地化字符串。
        /// </summary>
        internal static string itSchema {
            get {
                return ResourceManager.GetString("itSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stili 的本地化字符串。
        /// </summary>
        internal static string itStyles {
            get {
                return ResourceManager.GetString("itStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tabella 的本地化字符串。
        /// </summary>
        internal static string itTable {
            get {
                return ResourceManager.GetString("itTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progettazione tabelle 的本地化字符串。
        /// </summary>
        internal static string itTable_Designer {
            get {
                return ResourceManager.GetString("itTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Team 的本地化字符串。
        /// </summary>
        internal static string itTeam {
            get {
                return ResourceManager.GetString("itTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prova 的本地化字符串。
        /// </summary>
        internal static string itTest {
            get {
                return ResourceManager.GetString("itTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strumenti 的本地化字符串。
        /// </summary>
        internal static string itTools {
            get {
                return ResourceManager.GetString("itTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visualizza 的本地化字符串。
        /// </summary>
        internal static string itView {
            get {
                return ResourceManager.GetString("itView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finestra 的本地化字符串。
        /// </summary>
        internal static string itWindow {
            get {
                return ResourceManager.GetString("itWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML 的本地化字符串。
        /// </summary>
        internal static string itXML {
            get {
                return ResourceManager.GetString("itXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string jaAction {
            get {
                return ResourceManager.GetString("jaAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 アドイン 的本地化字符串。
        /// </summary>
        internal static string jaAddins {
            get {
                return ResourceManager.GetString("jaAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ビルド 的本地化字符串。
        /// </summary>
        internal static string jaBuild {
            get {
                return ResourceManager.GetString("jaBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 クラス ダイアグラム 的本地化字符串。
        /// </summary>
        internal static string jaClass_Diagram {
            get {
                return ResourceManager.GetString("jaClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 コミュニティ 的本地化字符串。
        /// </summary>
        internal static string jaCommunity {
            get {
                return ResourceManager.GetString("jaCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 データ 的本地化字符串。
        /// </summary>
        internal static string jaData {
            get {
                return ResourceManager.GetString("jaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 データベース 的本地化字符串。
        /// </summary>
        internal static string jaDatabase {
            get {
                return ResourceManager.GetString("jaDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 データベース ダイアグラム 的本地化字符串。
        /// </summary>
        internal static string jaDatabase_Diagram {
            get {
                return ResourceManager.GetString("jaDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 デバッグ 的本地化字符串。
        /// </summary>
        internal static string jaDebug {
            get {
                return ResourceManager.GetString("jaDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ダイアグラム 的本地化字符串。
        /// </summary>
        internal static string jaDiagram {
            get {
                return ResourceManager.GetString("jaDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 編集 的本地化字符串。
        /// </summary>
        internal static string jaEdit {
            get {
                return ResourceManager.GetString("jaEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ファイル 的本地化字符串。
        /// </summary>
        internal static string jaFile {
            get {
                return ResourceManager.GetString("jaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 書式 的本地化字符串。
        /// </summary>
        internal static string jaFormat {
            get {
                return ResourceManager.GetString("jaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 フレーム 的本地化字符串。
        /// </summary>
        internal static string jaFrames {
            get {
                return ResourceManager.GetString("jaFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ヘルプ 的本地化字符串。
        /// </summary>
        internal static string jaHelp {
            get {
                return ResourceManager.GetString("jaHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 イメージ 的本地化字符串。
        /// </summary>
        internal static string jaImage {
            get {
                return ResourceManager.GetString("jaImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レイアウト 的本地化字符串。
        /// </summary>
        internal static string jaLayout {
            get {
                return ResourceManager.GetString("jaLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 マクロ 的本地化字符串。
        /// </summary>
        internal static string jaMacros {
            get {
                return ResourceManager.GetString("jaMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 プロジェクト 的本地化字符串。
        /// </summary>
        internal static string jaProject {
            get {
                return ResourceManager.GetString("jaProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 クエリ 的本地化字符串。
        /// </summary>
        internal static string jaQuery {
            get {
                return ResourceManager.GetString("jaQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 クエリ デザイナ 的本地化字符串。
        /// </summary>
        internal static string jaQuery_Designer {
            get {
                return ResourceManager.GetString("jaQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 リファクタ 的本地化字符串。
        /// </summary>
        internal static string jaRefactor {
            get {
                return ResourceManager.GetString("jaRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 リソース 的本地化字符串。
        /// </summary>
        internal static string jaResources {
            get {
                return ResourceManager.GetString("jaResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スキーマ 的本地化字符串。
        /// </summary>
        internal static string jaSchema {
            get {
                return ResourceManager.GetString("jaSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スタイル 的本地化字符串。
        /// </summary>
        internal static string jaStyles {
            get {
                return ResourceManager.GetString("jaStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 テーブル 的本地化字符串。
        /// </summary>
        internal static string jaTable {
            get {
                return ResourceManager.GetString("jaTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 テーブル デザイナ 的本地化字符串。
        /// </summary>
        internal static string jaTable_Designer {
            get {
                return ResourceManager.GetString("jaTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 チーム 的本地化字符串。
        /// </summary>
        internal static string jaTeam {
            get {
                return ResourceManager.GetString("jaTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 テスト 的本地化字符串。
        /// </summary>
        internal static string jaTest {
            get {
                return ResourceManager.GetString("jaTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ツール 的本地化字符串。
        /// </summary>
        internal static string jaTools {
            get {
                return ResourceManager.GetString("jaTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示 的本地化字符串。
        /// </summary>
        internal static string jaView {
            get {
                return ResourceManager.GetString("jaView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィンドウ 的本地化字符串。
        /// </summary>
        internal static string jaWindow {
            get {
                return ResourceManager.GetString("jaWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML 的本地化字符串。
        /// </summary>
        internal static string jaXML {
            get {
                return ResourceManager.GetString("jaXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 작업 的本地化字符串。
        /// </summary>
        internal static string koAction {
            get {
                return ResourceManager.GetString("koAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 추가 기능 的本地化字符串。
        /// </summary>
        internal static string koAddins {
            get {
                return ResourceManager.GetString("koAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 빌드 的本地化字符串。
        /// </summary>
        internal static string koBuild {
            get {
                return ResourceManager.GetString("koBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 클래스 다이어그램 的本地化字符串。
        /// </summary>
        internal static string koClass_Diagram {
            get {
                return ResourceManager.GetString("koClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 커뮤니티 的本地化字符串。
        /// </summary>
        internal static string koCommunity {
            get {
                return ResourceManager.GetString("koCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 데이터 的本地化字符串。
        /// </summary>
        internal static string koData {
            get {
                return ResourceManager.GetString("koData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 데이터베이스 的本地化字符串。
        /// </summary>
        internal static string koDatabase {
            get {
                return ResourceManager.GetString("koDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 데이터베이스 다이어그램 的本地化字符串。
        /// </summary>
        internal static string koDatabase_Diagram {
            get {
                return ResourceManager.GetString("koDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 디버그 的本地化字符串。
        /// </summary>
        internal static string koDebug {
            get {
                return ResourceManager.GetString("koDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 다이어그램 的本地化字符串。
        /// </summary>
        internal static string koDiagram {
            get {
                return ResourceManager.GetString("koDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 편집 的本地化字符串。
        /// </summary>
        internal static string koEdit {
            get {
                return ResourceManager.GetString("koEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 파일 的本地化字符串。
        /// </summary>
        internal static string koFile {
            get {
                return ResourceManager.GetString("koFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 서식 的本地化字符串。
        /// </summary>
        internal static string koFormat {
            get {
                return ResourceManager.GetString("koFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 프레임 的本地化字符串。
        /// </summary>
        internal static string koFrames {
            get {
                return ResourceManager.GetString("koFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 도움말 的本地化字符串。
        /// </summary>
        internal static string koHelp {
            get {
                return ResourceManager.GetString("koHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 이미지 的本地化字符串。
        /// </summary>
        internal static string koImage {
            get {
                return ResourceManager.GetString("koImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 레이아웃 的本地化字符串。
        /// </summary>
        internal static string koLayout {
            get {
                return ResourceManager.GetString("koLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 매크로 的本地化字符串。
        /// </summary>
        internal static string koMacros {
            get {
                return ResourceManager.GetString("koMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 프로젝트 的本地化字符串。
        /// </summary>
        internal static string koProject {
            get {
                return ResourceManager.GetString("koProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿼리 的本地化字符串。
        /// </summary>
        internal static string koQuery {
            get {
                return ResourceManager.GetString("koQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿼리 디자이너 的本地化字符串。
        /// </summary>
        internal static string koQuery_Designer {
            get {
                return ResourceManager.GetString("koQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 리팩터링 的本地化字符串。
        /// </summary>
        internal static string koRefactor {
            get {
                return ResourceManager.GetString("koRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 리소스 的本地化字符串。
        /// </summary>
        internal static string koResources {
            get {
                return ResourceManager.GetString("koResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 스키마 的本地化字符串。
        /// </summary>
        internal static string koSchema {
            get {
                return ResourceManager.GetString("koSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 스타일 的本地化字符串。
        /// </summary>
        internal static string koStyles {
            get {
                return ResourceManager.GetString("koStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 테이블 的本地化字符串。
        /// </summary>
        internal static string koTable {
            get {
                return ResourceManager.GetString("koTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 테이블 디자이너 的本地化字符串。
        /// </summary>
        internal static string koTable_Designer {
            get {
                return ResourceManager.GetString("koTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 팀 的本地化字符串。
        /// </summary>
        internal static string koTeam {
            get {
                return ResourceManager.GetString("koTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 테스트 的本地化字符串。
        /// </summary>
        internal static string koTest {
            get {
                return ResourceManager.GetString("koTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 도구 的本地化字符串。
        /// </summary>
        internal static string koTools {
            get {
                return ResourceManager.GetString("koTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 뷰 的本地化字符串。
        /// </summary>
        internal static string koView {
            get {
                return ResourceManager.GetString("koView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 창 的本地化字符串。
        /// </summary>
        internal static string koWindow {
            get {
                return ResourceManager.GetString("koWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML 的本地化字符串。
        /// </summary>
        internal static string koXML {
            get {
                return ResourceManager.GetString("koXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string zh_CHSAction {
            get {
                return ResourceManager.GetString("zh-CHSAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外接程序 的本地化字符串。
        /// </summary>
        internal static string zh_CHSAddins {
            get {
                return ResourceManager.GetString("zh-CHSAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成 的本地化字符串。
        /// </summary>
        internal static string zh_CHSBuild {
            get {
                return ResourceManager.GetString("zh-CHSBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类关系图 的本地化字符串。
        /// </summary>
        internal static string zh_CHSClass_Diagram {
            get {
                return ResourceManager.GetString("zh-CHSClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 社区 的本地化字符串。
        /// </summary>
        internal static string zh_CHSCommunity {
            get {
                return ResourceManager.GetString("zh-CHSCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据 的本地化字符串。
        /// </summary>
        internal static string zh_CHSData {
            get {
                return ResourceManager.GetString("zh-CHSData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库 的本地化字符串。
        /// </summary>
        internal static string zh_CHSDatabase {
            get {
                return ResourceManager.GetString("zh-CHSDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库关系图 的本地化字符串。
        /// </summary>
        internal static string zh_CHSDatabase_Diagram {
            get {
                return ResourceManager.GetString("zh-CHSDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试 的本地化字符串。
        /// </summary>
        internal static string zh_CHSDebug {
            get {
                return ResourceManager.GetString("zh-CHSDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关系图 的本地化字符串。
        /// </summary>
        internal static string zh_CHSDiagram {
            get {
                return ResourceManager.GetString("zh-CHSDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string zh_CHSEdit {
            get {
                return ResourceManager.GetString("zh-CHSEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        internal static string zh_CHSFile {
            get {
                return ResourceManager.GetString("zh-CHSFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式 的本地化字符串。
        /// </summary>
        internal static string zh_CHSFormat {
            get {
                return ResourceManager.GetString("zh-CHSFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 框架 的本地化字符串。
        /// </summary>
        internal static string zh_CHSFrames {
            get {
                return ResourceManager.GetString("zh-CHSFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        internal static string zh_CHSHelp {
            get {
                return ResourceManager.GetString("zh-CHSHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像 的本地化字符串。
        /// </summary>
        internal static string zh_CHSImage {
            get {
                return ResourceManager.GetString("zh-CHSImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布局 的本地化字符串。
        /// </summary>
        internal static string zh_CHSLayout {
            get {
                return ResourceManager.GetString("zh-CHSLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宏 的本地化字符串。
        /// </summary>
        internal static string zh_CHSMacros {
            get {
                return ResourceManager.GetString("zh-CHSMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目 的本地化字符串。
        /// </summary>
        internal static string zh_CHSProject {
            get {
                return ResourceManager.GetString("zh-CHSProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        internal static string zh_CHSQuery {
            get {
                return ResourceManager.GetString("zh-CHSQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询设计器 的本地化字符串。
        /// </summary>
        internal static string zh_CHSQuery_Designer {
            get {
                return ResourceManager.GetString("zh-CHSQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重构 的本地化字符串。
        /// </summary>
        internal static string zh_CHSRefactor {
            get {
                return ResourceManager.GetString("zh-CHSRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源 的本地化字符串。
        /// </summary>
        internal static string zh_CHSResources {
            get {
                return ResourceManager.GetString("zh-CHSResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 架构 的本地化字符串。
        /// </summary>
        internal static string zh_CHSSchema {
            get {
                return ResourceManager.GetString("zh-CHSSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样式 的本地化字符串。
        /// </summary>
        internal static string zh_CHSStyles {
            get {
                return ResourceManager.GetString("zh-CHSStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表 的本地化字符串。
        /// </summary>
        internal static string zh_CHSTable {
            get {
                return ResourceManager.GetString("zh-CHSTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表设计器 的本地化字符串。
        /// </summary>
        internal static string zh_CHSTable_Designer {
            get {
                return ResourceManager.GetString("zh-CHSTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作组 的本地化字符串。
        /// </summary>
        internal static string zh_CHSTeam {
            get {
                return ResourceManager.GetString("zh-CHSTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试 的本地化字符串。
        /// </summary>
        internal static string zh_CHSTest {
            get {
                return ResourceManager.GetString("zh-CHSTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具 的本地化字符串。
        /// </summary>
        internal static string zh_CHSTools {
            get {
                return ResourceManager.GetString("zh-CHSTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视图 的本地化字符串。
        /// </summary>
        internal static string zh_CHSView {
            get {
                return ResourceManager.GetString("zh-CHSView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口 的本地化字符串。
        /// </summary>
        internal static string zh_CHSWindow {
            get {
                return ResourceManager.GetString("zh-CHSWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML 的本地化字符串。
        /// </summary>
        internal static string zh_CHSXML {
            get {
                return ResourceManager.GetString("zh-CHSXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 動作 的本地化字符串。
        /// </summary>
        internal static string zh_CHTAction {
            get {
                return ResourceManager.GetString("zh-CHTAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增益集 的本地化字符串。
        /// </summary>
        internal static string zh_CHTAddins {
            get {
                return ResourceManager.GetString("zh-CHTAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建置 的本地化字符串。
        /// </summary>
        internal static string zh_CHTBuild {
            get {
                return ResourceManager.GetString("zh-CHTBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 類別圖表 的本地化字符串。
        /// </summary>
        internal static string zh_CHTClass_Diagram {
            get {
                return ResourceManager.GetString("zh-CHTClass Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 社群 的本地化字符串。
        /// </summary>
        internal static string zh_CHTCommunity {
            get {
                return ResourceManager.GetString("zh-CHTCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 資料 的本地化字符串。
        /// </summary>
        internal static string zh_CHTData {
            get {
                return ResourceManager.GetString("zh-CHTData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 資料庫 的本地化字符串。
        /// </summary>
        internal static string zh_CHTDatabase {
            get {
                return ResourceManager.GetString("zh-CHTDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 資料庫圖表 的本地化字符串。
        /// </summary>
        internal static string zh_CHTDatabase_Diagram {
            get {
                return ResourceManager.GetString("zh-CHTDatabase Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 偵錯 的本地化字符串。
        /// </summary>
        internal static string zh_CHTDebug {
            get {
                return ResourceManager.GetString("zh-CHTDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圖表 的本地化字符串。
        /// </summary>
        internal static string zh_CHTDiagram {
            get {
                return ResourceManager.GetString("zh-CHTDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 編輯 的本地化字符串。
        /// </summary>
        internal static string zh_CHTEdit {
            get {
                return ResourceManager.GetString("zh-CHTEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 檔案 的本地化字符串。
        /// </summary>
        internal static string zh_CHTFile {
            get {
                return ResourceManager.GetString("zh-CHTFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式 的本地化字符串。
        /// </summary>
        internal static string zh_CHTFormat {
            get {
                return ResourceManager.GetString("zh-CHTFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 框架 的本地化字符串。
        /// </summary>
        internal static string zh_CHTFrames {
            get {
                return ResourceManager.GetString("zh-CHTFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 說明 的本地化字符串。
        /// </summary>
        internal static string zh_CHTHelp {
            get {
                return ResourceManager.GetString("zh-CHTHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 影像 的本地化字符串。
        /// </summary>
        internal static string zh_CHTImage {
            get {
                return ResourceManager.GetString("zh-CHTImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置 的本地化字符串。
        /// </summary>
        internal static string zh_CHTLayout {
            get {
                return ResourceManager.GetString("zh-CHTLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 巨集 的本地化字符串。
        /// </summary>
        internal static string zh_CHTMacros {
            get {
                return ResourceManager.GetString("zh-CHTMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 專案 的本地化字符串。
        /// </summary>
        internal static string zh_CHTProject {
            get {
                return ResourceManager.GetString("zh-CHTProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查詢 的本地化字符串。
        /// </summary>
        internal static string zh_CHTQuery {
            get {
                return ResourceManager.GetString("zh-CHTQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查詢設計工具 的本地化字符串。
        /// </summary>
        internal static string zh_CHTQuery_Designer {
            get {
                return ResourceManager.GetString("zh-CHTQuery Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重整 的本地化字符串。
        /// </summary>
        internal static string zh_CHTRefactor {
            get {
                return ResourceManager.GetString("zh-CHTRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 資源 的本地化字符串。
        /// </summary>
        internal static string zh_CHTResources {
            get {
                return ResourceManager.GetString("zh-CHTResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 結構描述 的本地化字符串。
        /// </summary>
        internal static string zh_CHTSchema {
            get {
                return ResourceManager.GetString("zh-CHTSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 樣式 的本地化字符串。
        /// </summary>
        internal static string zh_CHTStyles {
            get {
                return ResourceManager.GetString("zh-CHTStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 資料表 的本地化字符串。
        /// </summary>
        internal static string zh_CHTTable {
            get {
                return ResourceManager.GetString("zh-CHTTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 資料表設計工具 的本地化字符串。
        /// </summary>
        internal static string zh_CHTTable_Designer {
            get {
                return ResourceManager.GetString("zh-CHTTable Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小組 的本地化字符串。
        /// </summary>
        internal static string zh_CHTTeam {
            get {
                return ResourceManager.GetString("zh-CHTTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 測試 的本地化字符串。
        /// </summary>
        internal static string zh_CHTTest {
            get {
                return ResourceManager.GetString("zh-CHTTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具 的本地化字符串。
        /// </summary>
        internal static string zh_CHTTools {
            get {
                return ResourceManager.GetString("zh-CHTTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 檢視 的本地化字符串。
        /// </summary>
        internal static string zh_CHTView {
            get {
                return ResourceManager.GetString("zh-CHTView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 視窗 的本地化字符串。
        /// </summary>
        internal static string zh_CHTWindow {
            get {
                return ResourceManager.GetString("zh-CHTWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML 的本地化字符串。
        /// </summary>
        internal static string zh_CHTXML {
            get {
                return ResourceManager.GetString("zh-CHTXML", resourceCulture);
            }
        }
    }
}
