<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <Version>1.1.5</Version>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <BaseOutputPath>E:\BuffaloPackage</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ServerSocket.udp.cs.bak" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Buffalo.ArgCommon\Buffalo.ArgCommon.csproj" />
    <ProjectReference Include="..\Buffalo.Kernel\Buffalo.Kernel.csproj" />
  </ItemGroup>

</Project>
